### ISSUE TITLE
Installation instructions incorrect

### ISSUE THREAD

**Issue by rocketraman** [jdoss/slack-repo#3]
Thanks for this repo. Note that the installation instructions are incorrect. This is what copr shows:

![image](https://user-images.githubusercontent.com/53049/62552643-fb49a680-b83b-11e9-9990-d1a6ef7d96b5.png)

But I guess it should be:

```
dnf copr enable ...
dnf install slack-repo
dnf install slack
```

**Comment by jdoss** [comment]
Hey @rocketraman, I updated the install docs. Thanks!
