### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by sunshine69** [jdoss/slack-repo#6]
Hi there,

I tried 
```
dnf copr enable jdoss/slack -y

```

return an error

```
Error: This repository does not have any builds yet so you cannot enable it now.
```

Thought that might be dnf buggy frontend, I try manually deploy the repo file, however after that package `slack` is not available.

Please help to fix this?

Thanks

**Comment by jdoss** [comment]
Hey there, sorry for missing this. What distro and version are you trying to use this on? 

I am not sure why that is having issues but I just kicked off a build here https://copr.fedorainfracloud.org/coprs/jdoss/slack-repo/build/2107559/ and it should build things for almost every supported x86_64 arch distro/version on Copr.

**Comment by sunshine69** [comment]
> Hey there, sorry for missing this. What distro and version are you trying to use this on?
> 
> I am not sure why that is having issues but I just kicked off a build here https://copr.fedorainfracloud.org/coprs/jdoss/slack-repo/build/2107559/ and it should build things for almost every supported x86_64 arch distro/version on Copr.

Hi there, it is on fedora 32 at the time I tried.

I realized later on that actually slack does not have build for all fc version, they only have for fc22 or something, thus it might be the case. (even with their download). Using the download version even not build for fc32 seems to work as well so I just use the support version.

Thanks

**Comment by jdoss** [comment]
Slack doesn't build their specs correctly so they just reuse the FC22 spec they initially made when they launched Linux support. This repo doesn't provide anything other than a yum repository config so you can verify the RPM and update it automatically.
